name: CB_WEB_Terraform

on:
  push:
    branches:
      - main
    paths:
      - 'PROJECTS/CB_WEB/INFRA/**'
  pull_request:
    branches:
      - main
    paths:
      - 'PROJECTS/CB_WEB/INFRA/**'

jobs:
  TF-Workflow:
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      wdirectory: 'PROJECTS/CB_WEB/INFRA'
    secrets:
        aws-access-key-id: ${{ secrets.CB_WEB_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CB_WEB_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.CB_WEB_AWS_REGION }}
    