name: CB_WEB_Terraform_Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "destroy" to confirm'
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest

    if: ${{ github.event.inputs.confirm == 'destroy' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CB_WEB_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CB_WEB_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CB_WEB_AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: PROJECTS/CB_WEB/INFRA

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: PROJECTS/CB_WEB/INFRA