name: Terraform_Deploy

on:
  workflow_call:
    inputs:
      wdirectory:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-region:
        required: true
      

jobs:
  TF-Workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ secrets.aws-region }}

      - name: Terraform Format
        run: 
          cd "${{ inputs.wdirectory }}""
          terraform fmt

      - name: Terraform Init
        run: 
          cd "${{ inputs.wdirectory }}"
          terraform init
      
      - name: Terraform Validate
        run:  
          cd "${{ inputs.wdirectory }}"
          terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: 
          cd "${{ inputs.wdirectory }}"
          terraform plan -out=tfplan -input=false -no-color
        
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run:
          cd "${{ inputs.wdirectory }}" 
          terraform apply -auto-approve
        