name: Terraform Deploy

on:
  workflow_call:
    inputs:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-region:
        required: true
      wokring-directory:
        required: true
        type: string

jobs:
  TF-Workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ secrets.aws-region }}

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: terraform plan -out=tfplan -input=false -no-color
        working-directory: ${{ inputs.working-directory }}

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: ${{ inputs.working-directory }}