name: CB_WEB_Terraform

on:
  push:
    branches:
      - main
    paths:
      - 'PROJECTS/AWS/CB_WEB/INFRA/**'
  pull_request:
    branches:
      - main
    paths:
      - 'PROJECTS/AWS/CB_WEB/INFRA/**'

jobs:
  TF-Workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CB_WEB_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CB_WEB_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CB_WEB_AWS_REGION }}

      - name: Terraform Format
        run: terraform fmt
        working-directory: PROJECTS/CB_WEB/INFRA

      - name: Terraform Init
        run: terraform init
        working-directory: PROJECTS/CB_WEB/INFRA
      
      - name: Terraform Validate
        run: terraform validate
        working-directory: PROJECTS/CB_WEB/INFRA

      - name: Terraform Plan
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: terraform plan -out=tfplan -input=false -no-color
        working-directory: PROJECTS/CB_WEB/INFRA

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: PROJECTS/CB_WEB/INFRA